### ISSUE TITLE
Wrong fml translation key used, leading to crash when displaying loading errors

### ISSUE THREAD

**Issue by Erdragh** [thedarkcolour/KotlinForForge#105]
```
java.lang.IllegalArgumentException: When using FML translation keys, only use fml.modloadingissue. keys for mod loading issues: fml.modloading.javafml.dangling_entrypoint
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoadingIssue.<init>(ModLoadingIssue.java:30) ~[loader-4.0.24.jar%23132!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoadingIssue.<init>(ModLoadingIssue.java:24) ~[loader-4.0.24.jar%23132!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoadingIssue.error(ModLoadingIssue.java:35) ~[loader-4.0.24.jar%23132!/:4.0] {}
	at LAYER PLUGIN/kfflang.neoforge@5.4.0/thedarkcolour.kotlinforforge.neoforge.KotlinLanguageLoader.validate(KotlinLanguageLoader.kt:51) ~[kfflang-neoforge-5.4.0.jar%23193!/:5.4.0] {}
```
The line mentioned in this stacktrace uses `fml.modloading.[...]` instead of `fml.modloadingissue.[...]`:
https://github.com/thedarkcolour/KotlinForForge/blob/548c9dda4e4c184a05443e7bbbbcd16607a9008a/neoforge/kfflang/src/main/kotlin/thedarkcolour/kotlinforforge/neoforge/KotlinLanguageLoader.kt#L51

**Comment by thedarkcolour** [comment]
Gotta love breaking changes :/

**Comment by thedarkcolour** [comment]
Fixed in 5.5.0

**Comment by btwonion** [comment]
Hi,
would you mind releasing 5.5.0 or at least create a workflow for automatically building the mod?

**Comment by thedarkcolour** [comment]
Oops. Forgot to add it to Modrinth
