### ISSUE TITLE
Crashing with kotlinforforge installed

### ISSUE THREAD

**Issue by Toadteeth** [thedarkcolour/KotlinForForge#18]
I have a couple mods that require kotlin for forge to run but whenever i try to run the game with it installed it crashes every time.
I've tried just simply removing the mods that require kotlin but whenever i do that the game crashes as well for some reason.
heres the crash log:
Time: 4/25/21 4:50 PM
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.gui.fonts.FontResourceManager.<init>(SourceFile:48) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:451) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/3037451.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.rehash(ObjectOpenCustomHashSet.java:683) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.addOrGet(ObjectOpenCustomHashSet.java:360) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at net.minecraft.client.renderer.RenderType$Type.func_228676_c_(RenderType.java:1022) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.RenderType$Type.access$000(RenderType.java:987) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.RenderType.func_228633_a_(RenderType.java:577) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.RenderType.lambda$getText$18(RenderType.java:495) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.RenderType$$Lambda$10152/2010484538.get(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.RenderType.getRenderType(RenderType.java:721) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.RenderType.getRenderType(RenderType.java:684) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.RenderType.func_228658_l_(RenderType.java:492) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.gui.fonts.EmptyGlyph.<init>(SourceFile:10) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.gui.fonts.Font.<clinit>(Font.java:21) ~[?:?] {re:classloading,xf:OptiFine:default}
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.fonts.FontResourceManager.<init>(SourceFile:48) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:451) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/3037451.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

Any help would be greatly appreciated

**Comment by thedarkcolour** [comment]
Can you send the full log?

**Comment by ghoodsite** [comment]
I'm having the same issue with forge 36.1.2 / minecraft 1.16.5

**Comment by ghoodsite** [comment]
---- Minecraft Crash Report ----
// Oops.

Time: 5/4/21 6:10 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge_1.16.5.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge_1.16.5.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge_1.16.5.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge_1.16.5.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[forge:?] {re:classloading}
-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Mod File Bountiful-1.16.4-3.3.1.jar needs language provider kotlinforforge:1 or above to load
		We have found none
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_282] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge_1.16.5.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge_1.16.5.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge_1.16.5.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge_1.16.5.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 3.10.0-1160.21.1.el7.x86_64
	Java Version: 1.8.0_282, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 1559880040 bytes (1487 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 20 total; -Xmx2048M -Xms1331M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge_1.16.5.jar object_holder_definalize PLUGINSERVICE 
		/forge_1.16.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge_1.16.5.jar capability_inject_definalize PLUGINSERVICE 
		/forge_1.16.5.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge_1.16.5.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.8
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.8-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |NONE      |NOSIGNATURE
		forge-1.16.5-36.1.8-universal.jar                 |Forge                         |forge                         |36.1.8              |NONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90

**Comment by thedarkcolour** [comment]
Again, I need a log?

**Comment by thedarkcolour** [comment]
Your issue says you're missing KFF

**Comment by DJMcBirde** [comment]
I have the same problem. However KFF is installed.
![Screenshot 2021-05-28 145511](https://user-images.githubusercontent.com/84992871/120035897-f16ed580-bfc4-11eb-8eee-9bc4c36bc5d4.png)
![Screenshot 2021-05-28 145753](https://user-images.githubusercontent.com/84992871/120036056-2bd87280-bfc5-11eb-8672-6458da7bc405.png)

**Comment by thedarkcolour** [comment]
Crash report?

**Comment by thedarkcolour** [comment]
Try without OptiFine

**Comment by thedarkcolour** [comment]
Your OptiFine is also old

**Comment by DJMcBirde** [comment]
![Screenshot 2021-05-28 150128](https://user-images.githubusercontent.com/84992871/120036336-9e495280-bfc5-11eb-8115-d7c9d53dd737.png)

**Comment by DJMcBirde** [comment]
![Uploading Screenshot 2021-05-28 150235.png…]()

**Comment by DJMcBirde** [comment]
![Screenshot 2021-05-28 150235](https://user-images.githubusercontent.com/84992871/120036477-cd5fc400-bfc5-11eb-9fc2-e9cbe5c79b01.png)

**Comment by DJMcBirde** [comment]
![Screenshot 2021-05-28 150610](https://user-images.githubusercontent.com/84992871/120036780-42cb9480-bfc6-11eb-966a-b1443be59689.png)
I updated Optifine aswell.

**Comment by thedarkcolour** [comment]
Is BetterFoliage up to date?

**Comment by DJMcBirde** [comment]
Yes

**Comment by DJMcBirde** [comment]
![image](https://user-images.githubusercontent.com/84992871/120037417-37c53400-bfc7-11eb-8784-2b7d78a223af.png)

**Comment by DJMcBirde** [comment]
BetterFoliage-2.6.4-Forge-1.16.5

**Comment by DJMcBirde** [comment]
This is odd to me because I can run RLCraft 1.16.5 no problem.

**Comment by thedarkcolour** [comment]
Odd here as well cause I can run with BetterFoliage too

**Comment by DJMcBirde** [comment]
Is there a chance that it could be a actual "Language" problem? Like... windows language?

**Comment by DJMcBirde** [comment]
https://user-images.githubusercontent.com/84992871/120039149-0dc14100-bfca-11eb-98b6-74192af21eeb.mp4

**Comment by thedarkcolour** [comment]
testing it myself rn

**Comment by thedarkcolour** [comment]
With all your mods it's not crashing for me?

**Comment by DJMcBirde** [comment]
I don't know.

**Comment by DJMcBirde** [comment]
DJ_McBirde#5290
Discord. Copy and let me know so I can delete it

**Comment by thedarkcolour** [comment]
https://discord.gg/tmVmZtx

**Comment by thedarkcolour** [comment]
Kotlin for Forge discord

**Comment by Username404-59** [comment]
I don't think this is caused by kotlinforforge at all

**Comment by thedarkcolour** [comment]
Yep

**Comment by Username404-59** [comment]
Optifine might be the one crashing the game judging by the mixins errors

**Comment by thedarkcolour** [comment]
We resolved it in discord messages 
He had installed a 1.12.2 mod and immersive portals is only compatible with G7 optifine

**Comment by JaxxDivison** [comment]
Mine used to crash but now it loads but when it loads and I click the mods button its not there any fix?

**Comment by Rgvtto2009** [comment]
i want to install cobblemon but when i add j
kotlin it crashes i could send the crash log

**Comment by Rgvtto2009** [comment]
wait i cant see the crash log I only get the exit code which is 1
