### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by KP2048** [thedarkcolour/KotlinForForge#37]
```
[Architectury Transformer] Architectury Runtime 5.2.61
[Architectury Transformer] Read classpath in 1.251 s
[Architectury Transformer] Listening at C:\Users\Aaron\Documents\MCDEV\Minitect\common\build\devlibs\minitect-1.0.0-dev.jar
[09:56:15] [main/INFO] (Launcher) ModLauncher running: args [--launchTarget, forgeclientuserdev, --version, MOD_DEV, --assetIndex, 1.18.1-1.18, --assetsDir, C:\Users\Aaron\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.forgeVersion, 39.0.64, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[09:56:15] [main/INFO] (Launcher) ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Oracle Corporation
[09:56:15] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Aaron/.gradle/caches/transforms-3/9e6935665a35f7a393d0a2da1b84366e/transformed/alfd-transformed/mixin-patched-0.8.5.5.jar%2326!/ Service=ModLauncher Env=CLIENT
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file javafmllanguage-1.18.1-39.0.64.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@1994665d
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file mclanguage-1.18.1-39.0.64.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@1994665d
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file fmlcore-1.18.1-39.0.64.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@1994665d
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file forge-1.18.1-39.0.64-minecraft-merged-named.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@1994665d
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file main of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@1994665d
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file  of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@1994665d
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file kotlinforforge-1.16.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B021be081e0c3-B021be081e0c3.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file Bd7433bc2be85-Bd7433bc2be85.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file Bd711e31049cc-Bd711e31049cc.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B2e20f83d9414-B2e20f83d9414.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file Bb823ce43b211-Bb823ce43b211.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B68d30b3a6764-B68d30b3a6764.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B835e1676ca65-B835e1676ca65.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file 12473737401665767005.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file kotlinforforge-1.16.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B021be081e0c3-B021be081e0c3.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file Bd7433bc2be85-Bd7433bc2be85.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file Bd711e31049cc-Bd711e31049cc.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B2e20f83d9414-B2e20f83d9414.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file Bb823ce43b211-Bb823ce43b211.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B68d30b3a6764-B68d30b3a6764.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file B835e1676ca65-B835e1676ca65.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
[09:56:16] [main/INFO] (ModDiscoverer) Found mod file 12473737401665767005.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@77ec911
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "net.minecraftforge.forgespi.language.IModFileInfo.moduleName()" because the return value of "net.minecraftforge.forgespi.locating.IModFile.getModFileInfo()" is null
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.64/net.minecraftforge.fml.loading.moddiscovery.ModJarMetadata.name(ModJarMetadata.java:55)
	at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.impl.Jar.name(Jar.java:203)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:69)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:82)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:93)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)
```

**Comment by thedarkcolour** [comment]
Do you have a GitHub repo for this?

**Comment by KP2048** [comment]
Yes but I haven’t committed the switch to kotlin yet

**Comment by KP2048** [comment]
I can zip it up and post it here if you like

**Comment by thedarkcolour** [comment]
I don't know how you have the project set up, is it the same as [Adorn](https://github.com/Juuxel/Adorn/blob/1.18/forge/build.gradle.kts)

**Comment by thedarkcolour** [comment]
Yeah that would work

**Comment by KP2048** [comment]
it just gives an error saying `is not included in the list`

**Comment by thedarkcolour** [comment]
Change the file extension on it to something permitted

**Comment by KP2048** [comment]
https://drive.google.com/file/d/1MdcRZJDTdcDX0Wo5O4F3AqlGwdl2I_n_/view?usp=sharing

**Comment by KP2048** [comment]
zip files are on the list it was just being derpy

**Comment by thedarkcolour** [comment]
I'll look at it when I get home

**Comment by KP2048** [comment]
have you had a chance to look at it?

**Comment by thedarkcolour** [comment]
Looking at it now, I had a lot of homework yesterday

**Comment by thedarkcolour** [comment]
![image](https://user-images.githubusercontent.com/30441001/160213940-041a460b-80e2-44cb-9cdd-0a9a335759aa.png)
I don't know what this means

**Comment by thedarkcolour** [comment]
I can't figure out how to setup the project

**Comment by KP2048** [comment]
I got it working but now i have a different error

**Comment by KP2048** [comment]
And you must delete the .idea, build, and run folders in all the modules and submodules

**Comment by KP2048** [comment]
Then import it into idea

**Comment by KP2048** [comment]
Because it still has the paths for my computer

**Comment by thedarkcolour** [comment]
![image](https://user-images.githubusercontent.com/30441001/160219511-b1770fbd-8b60-432d-aed4-1a3c51de3674.png)
Now I have this error

**Comment by KP2048** [comment]
I figured it out :)
