### ISSUE TITLE
Error crash

### ISSUE THREAD

**Issue by LeonMazzoli** [thedarkcolour/KotlinForForge#71]
Exception in thread "main" java.lang.module.ResolutionException: Modules kotlin.stdlib and thedarkcolour.kotlinforforge export package kotlin.sequences to module usefulmachinery
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:755)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

I have this error for many different mods like JEI, YungsBetterDesert... Unable to launch my game :sob:, it's with new forge versions.

Please solve the problem :sob:

**Comment by thedarkcolour** [comment]
Can you please be more specific with your setup? What is your entire modlist? Your Minecraft version? Forge version? Kotlin for Forge version?

**Comment by LeonMazzoli** [comment]
[error.txt](https://github.com/thedarkcolour/KotlinForForge/files/11686556/error.txt)
Here is a file that contains all the info

**Comment by thedarkcolour** [comment]
Are you able to reproduce this outside of TLauncher?

**Comment by LeonMazzoli** [comment]
Here it is with the official launcher:
![error](https://github.com/thedarkcolour/KotlinForForge/assets/74470455/0be6eb00-bcd7-4063-9e8b-b0c1ed653c56)

**Comment by thedarkcolour** [comment]
Can you send the crash error from there?

**Comment by LeonMazzoli** [comment]
I have no crash reports

**Comment by thedarkcolour** [comment]
Check the .minecraft/logs folder for a file called "latest.log" or "debug.log"

**Comment by LeonMazzoli** [comment]
I changed my hard drive recently, without keeping the data from the old one. So I can't see if I had those files. But the error created no crash reports.

**Comment by thedarkcolour** [comment]
I can't really help without a debug.log, the error you sent from TLauncher didn't contain enough information (not to mention it's a pirated launcher)

**Comment by LeonMazzoli** [comment]
I now don't have the problem anymore, I'm sorry I couldn't give you more details and thanks anyway for your help
