### ISSUE TITLE
Kotlin reflection implementation is not found

### ISSUE THREAD

**Issue by creepinson** [thedarkcolour/KotlinForForge#9]
Sorry if this is dumb issue but I'm not sure what's causing this. I modified the kotlin modding template repository, ran the runData task in intellij idea's gradle tool window and it gave this and crashed:

```
[19:40:38] [modloading-worker-4/ERROR] [th.ko.LoggerKt/LOADING]: Failed to create mod instance. ModID: lightson, class example.examplemod.LightsOnMod
kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
	at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:84) ~[kotlin-stdlib-1.4.10.jar:1.4.10-release-411 (1.4.10)] {re:classloading}
	at kotlin.jvm.internal.ClassReference.getObjectInstance(ClassReference.kt:30) ~[kotlin-stdlib-1.4.10.jar:1.4.10-release-411 (1.4.10)] {re:classloading}
	at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:152) ~[?:1.6.2] {re:classloading}
	
```

**Comment by creepinson** [comment]
Hmm, it seems to be working now after deleting the gradle folder and gradle.properties and replacing them with the modding template files.

**Comment by creepinson** [comment]
I think I will close this, however I have a new issue with KDeferredRegisters.
